---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-uri-config
data:
  DATABASE: 'mongodb://ecommerce-deployment-mongo-service:27017/todo'

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: client-config
data:
  REACT_APP_API: "http:/todo.manrodri.com/api"